---
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

#project_name: doc
#release:
#  github:
#    owner: t-xinlin
#    name: doc

builds:
  - env:
      - CGO_ENABLED=0
    binary: doc
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags: -X main.Version={{.Version}} -X main.GitTag={{.Tag}} -X main.BuildDate={{.Date}}
